#!/usr/bin/python
def raise_exception():
    result = 5 + "String!! Oh no!!!"
